[package]
name = "celnakrblx/smartbone"
version = "0.1.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

include = ["src/SmartBone", "default.project.json", "LICENSE", "README.md","wally.toml"]
exclude = ["**"]

[dependencies]